# Generated by Django 4.2.3 on 2023-08-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account', models.IntegerField()),
                ('to_account', models.IntegerField()),
                ('status', models.CharField(choices=[('credit', 'CREDIT'), ('debit', 'DEBIT')], max_length=15)),
            ],
        ),
    ]
