# Generated by Django 4.2.3 on 2023-08-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='amount',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
