# Generated by Django 4.2.3 on 2023-08-10 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymenthistory_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='transation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
