# Generated by Django 4.2.4 on 2024-05-05 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('initiate', 'INITIATE'), ('success', 'SUCCESS'), ('fail', 'FAIL')], max_length=15)),
                ('transaction_id', models.CharField(max_length=200)),
                ('transaction_response', models.JSONField()),
                ('transaction_type', models.CharField(choices=[('esewa', 'ESEWA'), ('khalti', 'KHALTI'), ('others', 'OTHERS')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
